name: win32_registry
description: A set of classes for working with the Windows registry.
version: 1.0.0

environment:
  sdk: '>=2.17.0-16.0.dev <3.0.0'

dependencies: 
  ffi: ^1.1.2
  win32: ^2.3.5

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

