name: win32_registry
description: A set of helper classes for working with the Windows registry.
version: 1.1.1
homepage: https://win32.pub
repository: https://github.com/dart-windows/win32_registry
issue_tracker: https://github.com/dart-windows/win32_registry/issues

topics:
  - registry
  - win32
  - ffi
  - windows

environment:
  sdk: '^3.1.0'

platforms:
  windows:

dependencies:
  ffi: ^2.1.0
  win32: ^5.0.7

dev_dependencies:
  dartwindows_lints: ^1.0.0
  melos: ^3.1.1
  test: ^1.24.6
